CREATE TABLE "Cliente" (
    "idCliente" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nomeCliente" varchar2(255) NOT NULL,
    "cpfCnpjCliente" varchar2(20) NOT NULL,
    "telefoneCliente" varchar2(20),
    "emailCliente" varchar2(255),
    "enderecoCliente" varchar2(255),
    "dataCadastro" date DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY ("idCliente")
);

CREATE TABLE "Veiculo" (
    "idVeiculo" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "idCliente" number(10,0) NOT NULL,
    "placaVeiculo" varchar2(10) NOT NULL,
    "marcaVeiculo" varchar2(100) NOT NULL,
    "modeloVeiculo" varchar2(100) NOT NULL,
    "anoFabricacao" number(4,0) NOT NULL,
    "anoModelo" number(4,0) NOT NULL,
    "corVeiculo" varchar2(50),
    "quilometragemAtual" number(10,0),
    "chassiVeiculo" varchar2(30),
    PRIMARY KEY ("idVeiculo")
);

CREATE TABLE "Mecanico" (
    "idMecanico" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "codigoMecanico" varchar2(30) NOT NULL,
    "nomeMecanico" varchar2(255) NOT NULL,
    "enderecoMecanico" varchar2(255),
    "telefoneMecanico" varchar2(20),
    "especialidadeMecanico" varchar2(100) NOT NULL,
    "dataAdmissao" date NOT NULL,
    "statusMecanico" varchar2(30) NOT NULL,
    PRIMARY KEY ("idMecanico")
);

CREATE TABLE "Equipe" (
    "idEquipe" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nomeEquipe" varchar2(100) NOT NULL,
    "descricaoEquipe" varchar2(255),
    "statusEquipe" varchar2(30) NOT NULL,
    PRIMARY KEY ("idEquipe")
);

CREATE TABLE "EquipeMecanico" (
    "idEquipeMecanico" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "idEquipe" number(10,0) NOT NULL,
    "idMecanico" number(10,0) NOT NULL,
    "dataEntradaEquipe" date NOT NULL,
    "dataSaidaEquipe" date,
    "funcaoNaEquipe" varchar2(100),
    PRIMARY KEY ("idEquipeMecanico")
);

CREATE TABLE "Servicos" (
    "idServico" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "descricaoServico" varchar2(255) NOT NULL,
    "categoriaServico" varchar2(100) NOT NULL,
    "tempoEstimadoHoras" number(6,2),
    "statusServico" varchar2(30) NOT NULL,
    PRIMARY KEY ("idServico")
);

CREATE TABLE "Pecas" (
    "idPeca" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "codigoPeca" varchar2(50) NOT NULL,
    "nomePeca" varchar2(150) NOT NULL,
    "descricaoPeca" varchar2(255),
    "marcaPeca" varchar2(100),
    "valorUnitario" number(12,2) NOT NULL,
    "quantidadeEstoque" number(10,0) DEFAULT 0 NOT NULL,
    "estoqueMinimo" number(10,0) DEFAULT 0 NOT NULL,
    "statusPeca" varchar2(30) NOT NULL,
    PRIMARY KEY ("idPeca")
);

CREATE TABLE "MaoObra" (
    "idTabelaMaoObra" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "idServico" number(10,0) NOT NULL,
    "valorMaoObra" number(12,2) NOT NULL,
    "dataInicioVigencia" date NOT NULL,
    "dataFimVigencia" date,
    "statusTabela" varchar2(30) NOT NULL,
    PRIMARY KEY ("idTabelaMaoObra")
);

CREATE TABLE "OrdemServico" (
    "idOrdemServico" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "numeroOrdemServico" number(10,0) NOT NULL,
    "idCliente" number(10,0) NOT NULL,
    "idVeiculo" number(10,0) NOT NULL,
    "idEquipe" number(10,0) NOT NULL,
    "dataEmissao" date DEFAULT SYSDATE NOT NULL,
    "dataPrevistaConclusao" date NOT NULL,
    "dataConclusao" date,
    "valorTotal" number(12,2) DEFAULT 0 NOT NULL,
    "statusOrdemServico" varchar2(50) NOT NULL,
    "observacaoCliente" varchar2(500),
    "diagnosticoEquipe" varchar2(500),
    "autorizadaCliente" char(1) DEFAULT 'N' NOT NULL,
    "dataAutorizacao" date,
    PRIMARY KEY ("idOrdemServico")
);

CREATE TABLE "AutorizacaoServico" (
    "idAutorizacao" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "idOrdemServico" number(10,0) NOT NULL,
    "idCliente" number(10,0) NOT NULL,
    "dataAutorizacao" date NOT NULL,
    "statusAutorizacao" varchar2(30) NOT NULL,
    "formaAutorizacao" varchar2(50) NOT NULL,
    "observacaoAutorizacao" varchar2(500),
    PRIMARY KEY ("idAutorizacao")
);

CREATE TABLE "OrdemServicoServico" (
    "idOrdemServicoServico" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "idOrdemServico" number(10,0) NOT NULL,
    "idServico" number(10,0) NOT NULL,
    "idTabelaMaoObra" number(10,0),
    "quantidade" number(10,2) DEFAULT 1 NOT NULL,
    "valorUnitarioMaoObra" number(12,2) NOT NULL,
    "valorTotalServico" number(12,2) NOT NULL,
    "observacaoServico" varchar2(500),
    "statusServicoOS" varchar2(30) NOT NULL,
    PRIMARY KEY ("idOrdemServicoServico")
);

CREATE TABLE "OrdemServicoPeca" (
    "idOrdemServicoPeca" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "idOrdemServico" number(10,0) NOT NULL,
    "idPeca" number(10,0) NOT NULL,
    "quantidade" number(10,2) NOT NULL,
    "valorUnitarioPeca" number(12,2) NOT NULL,
    "valorTotalPeca" number(12,2) NOT NULL,
    PRIMARY KEY ("idOrdemServicoPeca")
);